# This file was generated by GoReleaser. DO NOT EDIT.
cask "airtruct" do
  name "airtruct"
  desc "Self-hosted ETL platform for data integration"
  homepage "https://github.com/sananguliyev/airtruct"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "airtruct"

  on_macos do
    on_intel do
      url "https://github.com/sananguliyev/airtruct/releases/download/v#{version}/airtruct_#{version}_darwin_amd64.tar.gz"
      sha256 "644d42f3fe8268ac5cea9e599200a8dbac71455db0236105409cf41c033d1602"
    end
    on_arm do
      url "https://github.com/sananguliyev/airtruct/releases/download/v#{version}/airtruct_#{version}_darwin_arm64.tar.gz"
      sha256 "d2d2a14da7b43207140ab0f4c88091cc34848f8048d4600c8f037fbb8fc90d2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sananguliyev/airtruct/releases/download/v#{version}/airtruct_#{version}_linux_amd64.tar.gz"
      sha256 "7f0aca4b81fff991506771718adeedb1a782d035e6940dca822d54c78facefe0"
    end
    on_arm do
      url "https://github.com/sananguliyev/airtruct/releases/download/v#{version}/airtruct_#{version}_linux_arm64.tar.gz"
      sha256 "596ee32770d14b302d569c9577ce6e2883d056bc8b6780d1336daf801041cd52"
    end
  end

  # No zap stanza required
end
