# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airtruct < Formula
  desc "Self-hosted ETL platform for data integration"
  homepage "https://github.com/sananguliyev/airtruct"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sananguliyev/airtruct/releases/download/v0.2.0/airtruct_0.2.0_darwin_amd64.tar.gz"
      sha256 "d3fefc427c964923d682851788088f47b503eaa72255990d62588093f52081dc"

      define_method(:install) do
        bin.install "airtruct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sananguliyev/airtruct/releases/download/v0.2.0/airtruct_0.2.0_darwin_arm64.tar.gz"
      sha256 "2eeb5864503ebb97b48d3701d8aebb2ec628f473ac0562f2de8c6c163c3705d5"

      define_method(:install) do
        bin.install "airtruct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sananguliyev/airtruct/releases/download/v0.2.0/airtruct_0.2.0_linux_amd64.tar.gz"
      sha256 "136516837d4ff2614ec1c70485dda3dd073c195ee0d90c336ac8c5206cd76ea8"
      define_method(:install) do
        bin.install "airtruct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sananguliyev/airtruct/releases/download/v0.2.0/airtruct_0.2.0_linux_arm64.tar.gz"
      sha256 "47f2fbc9d0a4273670866d70bcb6c46bce19127c254fcb30c3de0ba6c5d76d4d"
      define_method(:install) do
        bin.install "airtruct"
      end
    end
  end

  test do
    system "#{bin}/airtruct", "--version"
  end
end
